-- ============================================================================
-- Script Name:   03_customer_performance.sql
-- Task Number:   Task 8.3 - Customer Performance Analysis
-- Project Name:  Retail Sales & Customer Analytics (Aura Retail Group)
-- Database Name: RetailSalesAnalytics
-- Analysis Scope: Customer-level revenue, order volume, transaction frequency,
--                 profitability, ranking, revenue contribution, and NTILE(3)
--                 tertile segmentation.
-- Target Tables: dbo.FactSales, dbo.DimCustomer
-- Execution Note: All queries are strictly READ-ONLY analytical SELECT queries.
-- ============================================================================

USE [RetailSalesAnalytics];
GO

-- ============================================================================
-- 1. Total Customer Count
-- Business Question: What is the total count of registered customers?
-- Target Table: dbo.DimCustomer
-- ============================================================================
SELECT 
    COUNT(*) AS TotalCustomerCount
FROM dbo.DimCustomer;
GO

-- ============================================================================
-- 2. Customers with Purchases
-- Business Question: How many unique customers have placed at least one order?
-- Target Table: dbo.FactSales
-- ============================================================================
SELECT 
    COUNT(DISTINCT CustomerID) AS CustomersWithPurchases
FROM dbo.FactSales;
GO

-- ============================================================================
-- 3. Customers without Purchases
-- Business Question: How many registered customers have zero purchase history?
-- Methodology: LEFT JOIN between DimCustomer and FactSales filtering for NULLs.
-- ============================================================================
SELECT 
    COUNT(*) AS CustomersWithoutPurchases
FROM dbo.DimCustomer c
LEFT JOIN dbo.FactSales f 
    ON c.CustomerID = f.CustomerID
WHERE f.CustomerID IS NULL;
GO

-- ============================================================================
-- 4. Customer Revenue
-- Business Question: What is the total revenue generated by each customer?
-- Metric: SUM(SalesAmount) with NULL handling (0.00 for non-purchasers).
-- ============================================================================
WITH CustomerSales AS (
    SELECT 
        CustomerID,
        SUM(SalesAmount) AS TotalRevenue
    FROM dbo.FactSales
    GROUP BY CustomerID
)
SELECT 
    c.CustomerID,
    CONCAT(c.FirstName, ' ', c.LastName) AS CustomerName,
    COALESCE(cs.TotalRevenue, 0.00) AS TotalRevenue
FROM dbo.DimCustomer c
LEFT JOIN CustomerSales cs 
    ON c.CustomerID = cs.CustomerID
ORDER BY 
    TotalRevenue DESC;
GO

-- ============================================================================
-- 5. Customer Transaction Count
-- Business Question: How many distinct orders/transactions did each customer make?
-- Metric: COUNT(DISTINCT SalesID).
-- ============================================================================
WITH CustomerTransactions AS (
    SELECT 
        CustomerID,
        COUNT(DISTINCT SalesID) AS PurchaseCount
    FROM dbo.FactSales
    GROUP BY CustomerID
)
SELECT 
    c.CustomerID,
    CONCAT(c.FirstName, ' ', c.LastName) AS CustomerName,
    COALESCE(ct.PurchaseCount, 0) AS PurchaseCount
FROM dbo.DimCustomer c
LEFT JOIN CustomerTransactions ct 
    ON c.CustomerID = ct.CustomerID
ORDER BY 
    PurchaseCount DESC;
GO

-- ============================================================================
-- 6. Customer Quantity
-- Business Question: What is the total unit quantity purchased by each customer?
-- Metric: SUM(Quantity).
-- ============================================================================
WITH CustomerQuantities AS (
    SELECT 
        CustomerID,
        SUM(Quantity) AS TotalQuantity
    FROM dbo.FactSales
    GROUP BY CustomerID
)
SELECT 
    c.CustomerID,
    CONCAT(c.FirstName, ' ', c.LastName) AS CustomerName,
    COALESCE(cq.TotalQuantity, 0) AS TotalQuantity
FROM dbo.DimCustomer c
LEFT JOIN CustomerQuantities cq 
    ON c.CustomerID = cq.CustomerID
ORDER BY 
    TotalQuantity DESC;
GO

-- ============================================================================
-- 7. Average Order Value (AOV) per Customer
-- Business Question: What is the average sales revenue per order for each customer?
-- Metric: TotalRevenue / PurchaseCount with NULLIF division-by-zero protection.
-- ============================================================================
WITH CustomerAOV AS (
    SELECT 
        CustomerID,
        SUM(SalesAmount) AS TotalRevenue,
        COUNT(DISTINCT SalesID) AS PurchaseCount
    FROM dbo.FactSales
    GROUP BY CustomerID
)
SELECT 
    c.CustomerID,
    CONCAT(c.FirstName, ' ', c.LastName) AS CustomerName,
    ROUND(COALESCE(caov.TotalRevenue / NULLIF(caov.PurchaseCount, 0), 0.00), 2) AS AverageOrderValue
FROM dbo.DimCustomer c
LEFT JOIN CustomerAOV caov 
    ON c.CustomerID = caov.CustomerID
ORDER BY 
    AverageOrderValue DESC;
GO

-- ============================================================================
-- 8. Customer Profitability
-- Business Question: What is the revenue, cost, and net profit per customer?
-- Metrics: SUM(SalesAmount), SUM(CostAmount), SUM(Profit).
-- ============================================================================
WITH CustomerProfitability AS (
    SELECT 
        CustomerID,
        SUM(SalesAmount) AS TotalRevenue,
        SUM(CostAmount) AS TotalCost,
        SUM(Profit) AS TotalProfit
    FROM dbo.FactSales
    GROUP BY CustomerID
)
SELECT 
    c.CustomerID,
    CONCAT(c.FirstName, ' ', c.LastName) AS CustomerName,
    COALESCE(cp.TotalRevenue, 0.00) AS TotalRevenue,
    COALESCE(cp.TotalCost, 0.00) AS TotalCost,
    COALESCE(cp.TotalProfit, 0.00) AS TotalProfit
FROM dbo.DimCustomer c
LEFT JOIN CustomerProfitability cp 
    ON c.CustomerID = cp.CustomerID
ORDER BY 
    TotalProfit DESC;
GO

-- ============================================================================
-- 9. Top 10 Customers by Revenue
-- Business Question: Who are the top 10 highest-grossing customers?
-- Methodology: TOP (10) ordered by total revenue descending.
-- ============================================================================
SELECT TOP (10)
    c.CustomerID,
    CONCAT(c.FirstName, ' ', c.LastName) AS CustomerName,
    SUM(f.SalesAmount) AS TotalRevenue
FROM dbo.FactSales f
INNER JOIN dbo.DimCustomer c 
    ON f.CustomerID = c.CustomerID
GROUP BY 
    c.CustomerID,
    c.FirstName,
    c.LastName
ORDER BY 
    TotalRevenue DESC;
GO

-- ============================================================================
-- 10. Customer Revenue Ranking
-- Business Question: How do all customers rank based on gross revenue?
-- Window Function: DENSE_RANK() OVER (ORDER BY TotalRevenue DESC).
-- ============================================================================
WITH CustomerRevenueSummary AS (
    SELECT 
        CustomerID,
        SUM(SalesAmount) AS TotalRevenue
    FROM dbo.FactSales
    GROUP BY CustomerID
),
CustomerRankings AS (
    SELECT 
        c.CustomerID,
        CONCAT(c.FirstName, ' ', c.LastName) AS CustomerName,
        COALESCE(crs.TotalRevenue, 0.00) AS TotalRevenue
    FROM dbo.DimCustomer c
    LEFT JOIN CustomerRevenueSummary crs 
        ON c.CustomerID = crs.CustomerID
)
SELECT 
    CustomerID,
    CustomerName,
    TotalRevenue,
    DENSE_RANK() OVER (ORDER BY TotalRevenue DESC) AS RevenueRank
FROM CustomerRankings
ORDER BY 
    RevenueRank ASC,
    CustomerID ASC;
GO

-- ============================================================================
-- 11. Customer Revenue Contribution
-- Business Question: What percentage of total enterprise revenue is contributed by each customer?
-- Metric: (TotalRevenue * 100.0) / SUM(TotalRevenue) OVER () with NULLIF protection.
-- ============================================================================
WITH CustomerRevenueSummary AS (
    SELECT 
        CustomerID,
        SUM(SalesAmount) AS TotalRevenue
    FROM dbo.FactSales
    GROUP BY CustomerID
),
CustomerRevenueContribution AS (
    SELECT 
        c.CustomerID,
        CONCAT(c.FirstName, ' ', c.LastName) AS CustomerName,
        COALESCE(crs.TotalRevenue, 0.00) AS TotalRevenue
    FROM dbo.DimCustomer c
    LEFT JOIN CustomerRevenueSummary crs 
        ON c.CustomerID = crs.CustomerID
)
SELECT 
    CustomerID,
    CustomerName,
    TotalRevenue,
    ROUND((TotalRevenue * 100.0) / NULLIF(SUM(TotalRevenue) OVER (), 0), 4) AS RevenuePercentage
FROM CustomerRevenueContribution
ORDER BY 
    TotalRevenue DESC;
GO

-- ============================================================================
-- 12. Simple Customer Segmentation (NTILE)
-- Business Question: How are customers segmented into revenue performance tiers?
-- Methodology Note: NTILE(3) divides the customer base into three approximately
-- equal-sized groups (tertiles) ordered by total revenue descending:
--   - NTILE = 1 -> 'High Value'   (Top ~33.3% of customers by revenue)
--   - NTILE = 2 -> 'Medium Value' (Middle ~33.3% of customers by revenue)
--   - NTILE = 3 -> 'Low Value'    (Bottom ~33.3% of customers by revenue)
-- This approach is intentionally simple, deterministic, and highly efficient,
-- avoiding expensive percentile window functions (e.g., PERCENTILE_CONT).
-- ============================================================================
WITH CustomerRevenueSummary AS (
    SELECT 
        CustomerID,
        SUM(SalesAmount) AS TotalRevenue
    FROM dbo.FactSales
    GROUP BY CustomerID
),
CustomerRevenueWithNTILE AS (
    SELECT 
        c.CustomerID,
        CONCAT(c.FirstName, ' ', c.LastName) AS CustomerName,
        COALESCE(crs.TotalRevenue, 0.00) AS TotalRevenue,
        NTILE(3) OVER (ORDER BY COALESCE(crs.TotalRevenue, 0.00) DESC) AS RevenueBucket
    FROM dbo.DimCustomer c
    LEFT JOIN CustomerRevenueSummary crs 
        ON c.CustomerID = crs.CustomerID
)
SELECT 
    CustomerID,
    CustomerName,
    TotalRevenue,
    CASE RevenueBucket
        WHEN 1 THEN 'High Value'
        WHEN 2 THEN 'Medium Value'
        WHEN 3 THEN 'Low Value'
    END AS RevenueTier
FROM CustomerRevenueWithNTILE
ORDER BY 
    TotalRevenue DESC;
GO

-- ============================================================================
-- 13. Consolidated Customer Performance Summary
-- Business Question: What is the comprehensive performance snapshot for each customer?
-- Aggregates: Revenue, Cost, Profit, PurchaseCount, TotalQuantity, and AOV.
-- ============================================================================
WITH CustomerMetrics AS (
    SELECT 
        CustomerID,
        SUM(SalesAmount) AS TotalRevenue,
        SUM(CostAmount) AS TotalCost,
        SUM(Profit) AS TotalProfit,
        COUNT(DISTINCT SalesID) AS PurchaseCount,
        SUM(Quantity) AS TotalQuantity
    FROM dbo.FactSales
    GROUP BY CustomerID
)
SELECT 
    c.CustomerID,
    CONCAT(c.FirstName, ' ', c.LastName) AS CustomerName,
    COALESCE(cm.TotalRevenue, 0.00) AS TotalRevenue,
    COALESCE(cm.TotalCost, 0.00) AS TotalCost,
    COALESCE(cm.TotalProfit, 0.00) AS TotalProfit,
    COALESCE(cm.PurchaseCount, 0) AS PurchaseCount,
    COALESCE(cm.TotalQuantity, 0) AS TotalQuantity,
    ROUND(COALESCE(cm.TotalRevenue / NULLIF(cm.PurchaseCount, 0), 0.00), 2) AS AverageOrderValue
FROM dbo.DimCustomer c
LEFT JOIN CustomerMetrics cm 
    ON c.CustomerID = cm.CustomerID
ORDER BY 
    TotalRevenue DESC;
GO
